### ISSUE TITLE
ClusterIPAddress: New Resource

### ISSUE THREAD

**Issue by mnewswanger** [dsccommunity/FailoverClusterDsc#151]
**Details of the scenario you tried and the problem that is occurring:**
Add the ability to manipulate Cluster IP Addresses. This will allow the addition of multiple cluster IP resources for the cluster as well as manipulating the "Name" metadata property.  Cluster IP addresses are identified by IP Address & Network Mask combination.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System and PowerShell the DSC Target Node is running:**
This should be compatible with all versions

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
dev

**Comment by mnewswanger** [comment]
@johlju - While similar to Issue #92, I think it would make more sense to split this out to its own resource.   I'm planning on starting this early next week.

**Comment by johlju** [comment]
Thinking if xCluster could handle this? Today it only handles one static IP adress, but it should be able to take an array of IP addresses, and also be able to handle DHCP. See issue https://github.com/PowerShell/xFailOverCluster/issues/109. 
The name property of the Cluster IP Address might not be as easy to handle in the xCluster resource, so maybe this resource should handle that, but leave IP address (Static and DHCP) to the xCluster resource? 

What is you thoughts on this?
Also, could you please propose a schema.mof for this new resource?

**Comment by mnewswanger** [comment]
I think handling mulitple IPs could be done by the xCluster resource.  I'll play around with that a bit and see if I can get it working.  I don't think I want to scope DHCP assignment into this one - I don't think it'd be too crazy to do, but it's a different problem domain.

Re: xClusterIPAddress - I'm thinking it'd behave very similar to xClusterNetwork (modify metadata based on a unique IP / Netmask combination)

Proposed schema mof:
```powershell
[ClassVersion("1.0.0.0"), FriendlyName("xClusterIPAddress")]
class MSFT_xClusterIPAddress : OMI_BaseResource
{
    [Key, Description("The address for the cluster IP address in the format '10.0.0.0'.")] String Address;
    [Key, Description("The address mask for the cluster IP network in the format '255.255.255.0'.")] String AddressMask;
    [Write, Description("The name of the cluster address. If the cluster network name is not in desired state it will be renamed to match this name.")] String Name;
    [Write, Description("The state of the cluster address. Define if the cluster address should be enabled (Online) or disabled (Offline)"), ValueMap{"Online","Offline"}, Values{""Online", "Offline"}] String State;
};
```

**Comment by johlju** [comment]
If possible I like to see xCluster "adding and removing" IP-addresses, and this resource is changing the properties of those IP-addresses. Do you see it the same, or do you see a scenario? 

A suggestion, instead of the user needing to write 'Online' and 'Offline' for the `State` parameter, could the parameter instead be named `Enabled`, or `Online`, that is of type Boolean? What do you think?
So either:
`Enabled -eq $true` = Online
`Online -eq $true` = Online
`Enabled -eq $false` = Offline
`Online -eq $false` = Offline

Since the 'State' parameter will be used to bring online or take offline the resource, should the parameter not default to anything? Meaning if the user does not pass the parameter, no evaluation is done if the resource is in the correct state. 
If the 'State' should be online (or offline). then the resource will try to bring online (or take offline) the resource.

Btw. there is already a PR working on DHCP. I helping the contributor to get it over the finishing line, but haven't had the time to finish it yet (reviews take priority).
https://github.com/PowerShell/xFailOverCluster/pull/113

**Comment by mnewswanger** [comment]
I've been sidetracked from this project for a while, but I'm starting to look back into it.  The big push that I'm working on is setting up a multi-subnet failover cluster with an IP accessible on each of the target subnets.  While the subnets won't all exist on all nodes, the subnets will get added to the cluster.

Because the subnets are exclusive depending on the node, adding the IPs via xCluster would mean either a) running xCluster once with only one IP and then running xCluster again afterward (since it won't add the IP without having a subnet that matches from my quick testing) or b) running xCluster once and then using xClusterIP afterward to ensure the second IP gets added.  Either way, I think having xWaitforClusterNework will be necessary.  The workflow I'm thinking would be:

* xCluster creates the cluster (primary)
* xWaitforClusterNetwork waits for the second node to join (primary)
* xWaitforCluster waits for the cluster to exist (secondary)
* xCluster joins the second node to the cluster (secondary) -> This adds the second cluster network
* xWaitforClusterNetwork releases block (primary)
* xClusterIP adds the second IP to the cluster (primary)

While not perfect (and means that IPs get managed at two places), my thought is that the most likely scenario somebody would be doing this in the first place would be targeting multi-subnet capacity, and this would give a good workflow for that.

**Comment by johlju** [comment]
@mnewswanger If you run these steps manually, using the Failover Clustering cmdlets which the resource would use, do you get the expected behavior? The flow seems like it could work.

**Comment by Ziazmere** [comment]
Was there an Update on this thread for xfailovercluster and 2 IPs in differnet subnets for the CNO?
